on: 
  workflow_run:
    workflows: ["Create/Update"]
    types:
      - completed
name: Delete
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:    
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        # Specify the script here
        inlineScript: az group delete --name btd --yes
